import argparse
import csv
import glob
import json
import math
import statistics
from collections import defaultdict
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Rank FLUX2 transformer layers by redundancy using activation delta CSVs generated by "
            "analyze_flux2_activations.py."
        )
    )
    parser.add_argument(
        "--csv",
        nargs="*",
        default=None,
        help="Explicit CSV file paths. If omitted, --csv-glob is used.",
    )
    parser.add_argument(
        "--csv-glob",
        type=str,
        default="activation_plots/**/layer_activation_deltas_pipeline.csv",
        help="Glob pattern used when --csv is not provided.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("activation_plots/redundancy_report"),
        help="Directory for ranking outputs.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=20,
        help="Number of top removal candidates to print and save.",
    )
    parser.add_argument(
        "--hidden-weight",
        type=float,
        default=0.5,
        help="Weight for hidden_states stream in combined importance.",
    )
    parser.add_argument(
        "--encoder-weight",
        type=float,
        default=0.5,
        help="Weight for encoder_hidden_states stream in combined importance.",
    )
    parser.add_argument(
        "--importance-mean-weight",
        type=float,
        default=0.6,
        help="Weight for mean delta when computing importance score.",
    )
    parser.add_argument(
        "--importance-peak-weight",
        type=float,
        default=0.3,
        help="Weight for peak delta when computing importance score.",
    )
    parser.add_argument(
        "--importance-std-weight",
        type=float,
        default=0.1,
        help="Weight for timestep-variance delta when computing importance score.",
    )
    parser.add_argument(
        "--protect-final-double",
        type=int,
        default=0,
        help="Mark last N double-stream blocks as protected (not suggested for removal).",
    )
    parser.add_argument(
        "--protect-final-single",
        type=int,
        default=0,
        help="Mark last N single-stream blocks as protected (not suggested for removal).",
    )
    parser.add_argument(
        "--protect-layers",
        type=str,
        default="",
        help="Comma-separated explicit layer names to protect (example: double_04,single_19).",
    )
    return parser.parse_args()


def find_csv_files(args: argparse.Namespace) -> list[Path]:
    files = []
    if args.csv:
        files = [Path(x) for x in args.csv]
    else:
        files = [Path(x) for x in glob.glob(args.csv_glob, recursive=True)]
    files = [p for p in files if p.exists()]
    if not files:
        raise FileNotFoundError(
            "No CSV files found. Provide --csv path(s) or adjust --csv-glob."
        )
    return sorted(files)


def parse_float(value):
    if value is None:
        return None
    text = str(value).strip()
    if text == "" or text.lower() == "nan":
        return None
    return float(text)


def parse_weight(value):
    v = parse_float(value)
    if v is None or v <= 0:
        return 1.0
    return float(v)


def parse_layer_name(layer_name: str) -> tuple[str, int]:
    parts = layer_name.split("_")
    if len(parts) != 2:
        return ("other", -1)
    try:
        return (parts[0], int(parts[1]))
    except ValueError:
        return (parts[0], -1)


def layer_sort_key(layer_name: str):
    stream, idx = parse_layer_name(layer_name)
    group = 0 if stream == "double" else 1 if stream == "single" else 2
    return (group, idx, layer_name)


def weighted_stream_combine(hidden_value, encoder_value, hidden_weight, encoder_weight):
    pairs = []
    if hidden_value is not None:
        pairs.append((hidden_value, hidden_weight))
    if encoder_value is not None:
        pairs.append((encoder_value, encoder_weight))
    if not pairs:
        return None
    denom = sum(w for _, w in pairs)
    if denom <= 0:
        return float(sum(v for v, _ in pairs) / len(pairs))
    return float(sum(v * w for v, w in pairs) / denom)


def load_and_aggregate(csv_files: list[Path]):
    # layer -> timestep -> aggregated weighted sums
    aggregate = defaultdict(
        lambda: defaultdict(
            lambda: {
                "hidden_sum": 0.0,
                "hidden_w": 0.0,
                "encoder_sum": 0.0,
                "encoder_w": 0.0,
            }
        )
    )

    for csv_path in csv_files:
        with csv_path.open("r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                layer = str(row.get("layer", "")).strip()
                if not layer:
                    continue
                timestep = parse_float(row.get("raw_timestep"))
                if timestep is None:
                    continue

                hidden = parse_float(row.get("hidden_states_abs_delta_mean"))
                encoder = parse_float(row.get("encoder_hidden_states_abs_delta_mean"))

                hidden_weight = parse_weight(row.get("num_hidden_samples"))
                encoder_weight = parse_weight(row.get("num_encoder_samples"))

                slot = aggregate[layer][timestep]
                if hidden is not None:
                    slot["hidden_sum"] += hidden * hidden_weight
                    slot["hidden_w"] += hidden_weight
                if encoder is not None:
                    slot["encoder_sum"] += encoder * encoder_weight
                    slot["encoder_w"] += encoder_weight

    return aggregate


def build_layer_stats(aggregate, hidden_weight: float, encoder_weight: float):
    stats = {}
    for layer, timestep_map in aggregate.items():
        combined_series = []
        hidden_series = []
        encoder_series = []
        timesteps = sorted(timestep_map.keys(), reverse=True)
        total_hidden_samples = 0.0
        total_encoder_samples = 0.0

        for t in timesteps:
            slot = timestep_map[t]
            hidden = None
            encoder = None

            if slot["hidden_w"] > 0:
                hidden = slot["hidden_sum"] / slot["hidden_w"]
                hidden_series.append(hidden)
            if slot["encoder_w"] > 0:
                encoder = slot["encoder_sum"] / slot["encoder_w"]
                encoder_series.append(encoder)

            total_hidden_samples += slot["hidden_w"]
            total_encoder_samples += slot["encoder_w"]

            combined = weighted_stream_combine(hidden, encoder, hidden_weight, encoder_weight)
            if combined is not None:
                combined_series.append(combined)

        if not combined_series:
            continue

        mean_combined = statistics.fmean(combined_series)
        peak_combined = max(combined_series)
        std_combined = statistics.pstdev(combined_series) if len(combined_series) > 1 else 0.0
        mean_hidden = statistics.fmean(hidden_series) if hidden_series else float("nan")
        mean_encoder = statistics.fmean(encoder_series) if encoder_series else float("nan")

        stream_name, layer_idx = parse_layer_name(layer)
        stats[layer] = {
            "stream": stream_name,
            "index": layer_idx,
            "timesteps_covered": len(combined_series),
            "combined_mean_delta": mean_combined,
            "combined_peak_delta": peak_combined,
            "combined_std_delta": std_combined,
            "hidden_mean_delta": mean_hidden,
            "encoder_mean_delta": mean_encoder,
            "total_hidden_samples": int(round(total_hidden_samples)),
            "total_encoder_samples": int(round(total_encoder_samples)),
        }

    return stats


def minmax_normalizer(values):
    if not values:
        return (0.0, 0.0)
    return (min(values), max(values))


def minmax_scale(value, minimum, maximum):
    if math.isclose(minimum, maximum):
        return 0.5
    return (value - minimum) / (maximum - minimum)


def get_protected_layers(
    stats,
    protect_final_double: int,
    protect_final_single: int,
    explicit_layers: list[str],
):
    protected = set(explicit_layers)

    doubles = sorted(
        [name for name, s in stats.items() if s["stream"] == "double"],
        key=lambda x: stats[x]["index"],
    )
    singles = sorted(
        [name for name, s in stats.items() if s["stream"] == "single"],
        key=lambda x: stats[x]["index"],
    )

    if protect_final_double > 0:
        protected.update(doubles[-protect_final_double:])
    if protect_final_single > 0:
        protected.update(singles[-protect_final_single:])
    return protected


def rank_layers(
    stats,
    mean_w: float,
    peak_w: float,
    std_w: float,
    protected: set[str],
):
    mean_min, mean_max = minmax_normalizer([s["combined_mean_delta"] for s in stats.values()])
    peak_min, peak_max = minmax_normalizer([s["combined_peak_delta"] for s in stats.values()])
    std_min, std_max = minmax_normalizer([s["combined_std_delta"] for s in stats.values()])

    for layer, s in stats.items():
        mean_n = minmax_scale(s["combined_mean_delta"], mean_min, mean_max)
        peak_n = minmax_scale(s["combined_peak_delta"], peak_min, peak_max)
        std_n = minmax_scale(s["combined_std_delta"], std_min, std_max)
        importance = mean_w * mean_n + peak_w * peak_n + std_w * std_n
        redundancy = 1.0 - importance
        s["importance_score"] = float(importance)
        s["redundancy_score"] = float(redundancy)
        s["removable"] = layer not in protected

    ranked = sorted(
        stats.keys(),
        key=lambda name: (
            -stats[name]["redundancy_score"],
            stats[name]["combined_mean_delta"],
            layer_sort_key(name),
        ),
    )
    return ranked


def save_outputs(
    output_dir: Path,
    ranked_layers: list[str],
    stats,
    csv_files: list[Path],
    args: argparse.Namespace,
):
    output_dir.mkdir(parents=True, exist_ok=True)

    ranking_csv = output_dir / "layer_redundancy_ranking.csv"
    with ranking_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "rank",
                "layer",
                "stream",
                "index",
                "redundancy_score",
                "importance_score",
                "combined_mean_delta",
                "combined_peak_delta",
                "combined_std_delta",
                "hidden_mean_delta",
                "encoder_mean_delta",
                "timesteps_covered",
                "total_hidden_samples",
                "total_encoder_samples",
                "removable",
            ]
        )
        for rank, layer in enumerate(ranked_layers, start=1):
            s = stats[layer]
            writer.writerow(
                [
                    rank,
                    layer,
                    s["stream"],
                    s["index"],
                    s["redundancy_score"],
                    s["importance_score"],
                    s["combined_mean_delta"],
                    s["combined_peak_delta"],
                    s["combined_std_delta"],
                    s["hidden_mean_delta"],
                    s["encoder_mean_delta"],
                    s["timesteps_covered"],
                    s["total_hidden_samples"],
                    s["total_encoder_samples"],
                    s["removable"],
                ]
            )

    removable = [name for name in ranked_layers if stats[name]["removable"]]
    top_k = min(max(args.top_k, 0), len(removable))

    removal_txt = output_dir / "suggested_removal_order.txt"
    with removal_txt.open("w", encoding="utf-8") as f:
        f.write("Suggested removal order (most redundant first; heuristic):\n")
        for i, layer in enumerate(removable[:top_k], start=1):
            s = stats[layer]
            f.write(
                f"{i:02d}. {layer} "
                f"(redundancy={s['redundancy_score']:.4f}, "
                f"mean_delta={s['combined_mean_delta']:.6f}, "
                f"peak_delta={s['combined_peak_delta']:.6f})\n"
            )

    meta = {
        "csv_files": [str(p.resolve()) for p in csv_files],
        "num_layers": len(ranked_layers),
        "num_removable_layers": len(removable),
        "hidden_weight": args.hidden_weight,
        "encoder_weight": args.encoder_weight,
        "importance_mean_weight": args.importance_mean_weight,
        "importance_peak_weight": args.importance_peak_weight,
        "importance_std_weight": args.importance_std_weight,
        "protect_final_double": args.protect_final_double,
        "protect_final_single": args.protect_final_single,
        "protect_layers": [x.strip() for x in args.protect_layers.split(",") if x.strip()],
        "top_k": args.top_k,
    }
    with (output_dir / "redundancy_metadata.json").open("w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

    return ranking_csv, removal_txt, removable


def main():
    args = parse_args()
    csv_files = find_csv_files(args)

    aggregate = load_and_aggregate(csv_files)
    stats = build_layer_stats(aggregate, args.hidden_weight, args.encoder_weight)
    if not stats:
        raise RuntimeError("No valid layer statistics could be computed from the provided CSV files.")

    explicit_protect = [x.strip() for x in args.protect_layers.split(",") if x.strip()]
    protected_layers = get_protected_layers(
        stats,
        protect_final_double=args.protect_final_double,
        protect_final_single=args.protect_final_single,
        explicit_layers=explicit_protect,
    )

    ranked_layers = rank_layers(
        stats,
        mean_w=args.importance_mean_weight,
        peak_w=args.importance_peak_weight,
        std_w=args.importance_std_weight,
        protected=protected_layers,
    )

    ranking_csv, removal_txt, removable = save_outputs(
        args.output_dir,
        ranked_layers,
        stats,
        csv_files,
        args,
    )

    print(f"Loaded CSV files: {len(csv_files)}")
    print(f"Layers ranked: {len(ranked_layers)}")
    print(f"Ranking CSV: {ranking_csv.resolve()}")
    print(f"Suggested removal order: {removal_txt.resolve()}")
    print("")
    print("Top removal candidates (heuristic):")
    top_k = min(max(args.top_k, 0), len(removable))
    for i, layer in enumerate(removable[:top_k], start=1):
        s = stats[layer]
        print(
            f"{i:02d}. {layer} | redundancy={s['redundancy_score']:.4f} | "
            f"mean_delta={s['combined_mean_delta']:.6f} | peak_delta={s['combined_peak_delta']:.6f}"
        )


if __name__ == "__main__":
    main()
