python main.py \
    --model_path  /your/path/to/model \
    --prune_method OBS-Diff-Structured \
    --seed 24432 \
    --sparsity_ratio 0.20 \
    --sparsity_type structured \
    --timestep_weight_strategy log_decrease \
    --timestep_min_weight 0.8 \
    --timestep_max_weight 1.2 \
    --minlayer 0 \
    --maxlayer 23 \
    --dataset gcc3m \
    --num_samples 100 \
    --num_inference_steps 25 \
    --batch_size 4 \
    --height 512 \
    --width 512 \
    --guidance_scale 7.0 \
    --num_pruned_groups 4 \
    --save_model /your/path/to/save/model \
    --demo_evaluate \
    --demo_dir OBS_Diff_Structured_test.png